XXXXX: Include lib for git install
Somehow, using "prepare" script in "package.json" cause following error and I ended up to solve this.

    ./src/index.ts → ./lib/index.js...
    (!) Error when using sourcemap for reporting an error: Can't resolve original location of error.
    src/utils/getJSXFromRenderFn.ts: (1:9)
    [!] Error: '__spreadArrays' is not exported by tslib
    https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module
    src/utils/getJSXFromRenderFn.ts (1:9)
    1: import { AsyncComponent, Component, VNodeData } from 'vue'
                ^
    2:
    3: import { AnyComponent } from '../types/vue'
    Error: '__spreadArrays' is not exported by tslib
        at error (/private/tmp/empty-cache/_cacache/tmp/git-clone-3a8a7adf/node_modules/rollup/dist/rollup.js:9419:30)
        at Module.error (/private/tmp/empty-cache/_cacache/tmp/git-clone-3a8a7adf/node_modules/rollup/dist/rollup.js:13402:9)
        at handleMissingExport (/private/tmp/empty-cache/_cacache/tmp/git-clone-3a8a7adf/node_modules/rollup/dist/rollup.js:13322:21)
        at Module.traceVariable (/private/tmp/empty-cache/_cacache/tmp/git-clone-3a8a7adf/node_modules/rollup/dist/rollup.js:13711:17)
        at ModuleScope.findVariable (/private/tmp/empty-cache/_cacache/tmp/git-clone-3a8a7adf/node_modules/rollup/dist/rollup.js:12414:39)
        at FunctionScope.findVariable (/private/tmp/empty-cache/_cacache/tmp/git-clone-3a8a7adf/node_modules/rollup/dist/rollup.js:2981:38)
        at ChildScope.findVariable (/private/tmp/empty-cache/_cacache/tmp/git-clone-3a8a7adf/node_modules/rollup/dist/rollup.js:2981:38)
        at Identifier$1.bind (/private/tmp/empty-cache/_cacache/tmp/git-clone-3a8a7adf/node_modules/rollup/dist/rollup.js:8340:40)
        at CallExpression$1.bind (/private/tmp/empty-cache/_cacache/tmp/git-clone-3a8a7adf/node_modules/rollup/dist/rollup.js:7969:23)
        at CallExpression$1.bind (/private/tmp/empty-cache/_cacache/tmp/git-clone-3a8a7adf/node_modules/rollup/dist/rollup.js:10361:15)
        at MemberExpression.bind (/private/tmp/empty-cache/_cacache/tmp/git-clone-3a8a7adf/node_modules/rollup/dist/rollup.js:7969:23)
        at MemberExpression.bind (/private/tmp/empty-cache/_cacache/tmp/git-clone-3a8a7adf/node_modules/rollup/dist/rollup.js:11347:19)
        at MemberExpression.getReturnExpressionWhenCalledAtPath (/private/tmp/empty-cache/_cacache/tmp/git-clone-3a8a7adf/node_modules/rollup/dist/rollup.js:11384:18)
        at CallExpression$1.getLiteralValueAtPath (/private/tmp/empty-cache/_cacache/tmp/git-clone-3a8a7adf/node_modules/rollup/dist/rollup.js:10404:49)
        at CallExpression$1.getLiteralValueAtPath (/private/tmp/empty-cache/_cacache/tmp/git-clone-3a8a7adf/node_modules/rollup/dist/rollup.js:10411:38)
        at LocalVariable.getLiteralValueAtPath (/private/tmp/empty-cache/_cacache/tmp/git-clone-3a8a7adf/node_modules/rollup/dist/rollup.js:2809:26)

    error An unexpected error occurred: "Command failed.
    Exit code: 1